<%@ Page Title="" Language="C#" MasterPageFile="~/KPMG.master" AutoEventWireup="true" CodeFile="TripPage.aspx.cs" Inherits="TripPage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <link href="App_Themes/Baker/Content/Login.css" rel="stylesheet" type="text/css" />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="cpMainContent" Runat="Server">
    <style type="text/css">
    @font-face{
	font-family: 'aller';
	src: url('fonts/Aller/Aller_Rg.ttf') format('truetype');
	font-weight: normal;
	font-style: normal;
	}
    body {background-image: url("App_Themes/Baker/Images/buildingbg.jpg");
          background-repeat: no-repeat;
          font-family: 'aller';
          opacity: 0.8;
    }
    .navbar-header {
        background-color: white;
    }

	.rounded-box {
	background-color: white;
    /*opacity: 0.8;*/
	color: #000;
	position: relative;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
	border-radius: 10px;
	border-top: 1px solid #ddd;
	border-left: 1px solid #ddd;
	border-bottom: 1px solid #ddd;
	border-right: 1px solid #ddd;
	padding: 10px 10px;
	margin-left: auto;
	margin-right: auto;
}
	input[type="submit"],
	input[type="button"],
	button {
		border: 1px solid #a99f9a;
        padding: 3px 8px;
        background-color: white;
        cursor: pointer;
		font-size: medium;
		font-weight: 600;
		margin-right: 6px;
		width: auto;
		-moz-border-radius: 5px;
		-webkit-border-radius: 5px;
		border-radius: 5px;
        font-family: 'aller';
        margin-left: 22px;
    }
                    

      #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }


        </style>

<div style="margin-top: 10px; margin-left:auto; margin-right:auto; width: 80%; background-color: #F7F7F7;">
    <br />
    <h2 style="margin-top:10px; margin-left:10px; font-weight:bold;">Reservations Summary</h2>
	<hr style="margin-top:4px; margin-bottom: 8px;" />

        <asp:Panel ID="Panel2" runat="server">
            <table class="auto-style2">
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        &nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>
                        <asp:Panel ID="Panel6" runat="server">
                            <br />
                        </asp:Panel>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">
                        <asp:Label ID="FlightSummaryLabel0" runat="server" style="font-size: large" Text="Flight Booking Summary"></asp:Label>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">
                        <asp:GridView ID="FlightSummaryGridView" runat="server" AutoGenerateColumns="true" AutoGenerateDeleteButton="True" BackColor="Silver" Height="90%" style="color: #333333; background-color: #E3E3E3" Width="100%" AllowPaging="true" OnPageIndexChanging="FlightSummaryGridView_PageIndexChanging">
                        </asp:GridView>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">
                        <asp:Label ID="TrainSummaryLabel1" runat="server" style="font-size: large" Text="Train Booking Summary"></asp:Label>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">
                        <asp:GridView ID="TrainSummaryGridView" runat="server" AutoGenerateColumns="true" AutoGenerateDeleteButton="True" BackColor="Silver" Height="90%" style="color: #333333; background-color: #E3E3E3" Width="100%">
                        </asp:GridView>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">
                        <asp:Label ID="HotelSummaryLabel0" runat="server" style="font-size: large" Text="Hotel Booking Summary"></asp:Label>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">
                        <asp:GridView ID="HotelSummaryGridView" runat="server" AutoGenerateColumns="true" AutoGenerateDeleteButton="True" BackColor="Silver" Height="90%" style="color: #333333; background-color: #E3E3E3" Width="100%">
                        </asp:GridView>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">
                        <asp:Label ID="CarSummaryLabel" runat="server" style="font-size: large" Text="Car Booking Summary"></asp:Label>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">
                        <asp:GridView ID="CarSummaryGridView" runat="server" AutoGenerateColumns="true" AutoGenerateDeleteButton="True" BackColor="Silver" Height="90%" style="color: #333333; background-color: #E3E3E3" Width="100%">
                        </asp:GridView>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align:center" colspan="4">
                        <asp:Label ID="lblTripTotal" runat="server" style="font-size: x-large; color: #1F397E;" Text="Your Trip Total:"></asp:Label>
                        <asp:Label ID="txtTripName" runat="server" Text="TripName"></asp:Label>
                        <br />
                        <asp:TextBox ID="TripTotal" runat="server" BackColor="Silver" Height="30px" ReadOnly="True" Width="160px"></asp:TextBox>
                        <asp:TextBox ID="TextBox1" runat="server" Height="24px" Width="141px"></asp:TextBox>
                        <br />
                        <asp:Label ID="lblOutPolicy" runat="server" ForeColor="Red" Text="*Total amount is OUT OF POLICY. Please provide a reason for the exceptional total below." Visible="False"></asp:Label>
                        <br />
                        <asp:DropDownList ID="DDLReason" runat="server" Visible="False">
                            <asp:ListItem>Prior Approval Given</asp:ListItem>
                            <asp:ListItem>Last Minute Priority</asp:ListItem>
                            <asp:ListItem>I will pay the difference</asp:ListItem>
                            <asp:ListItem>Using previous credit</asp:ListItem>
                        </asp:DropDownList>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td style="background-color: #F7F7F7; text-align:center" colspan="4">
<%--                        <asp:Button ID="BookButton" runat="server" CssClass="roundInputs" Height="48px" OnClick="BookButton_Click" Text="BOOK IT!!" Width="177px" />--%>

                        <asp:Button ID="BookButton" runat="server" Text="BOOK IT!" CssClass="roundInputs" BackColor="#DA7E28" BorderColor="Yellow" Height="57px" Width="147px" OnClick="BookButton_Click" />
                        <asp:Button ID="ExportToExcel" runat="server" OnClick="ExportToExcel_Click" Text="ExportToExcel" />
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="4">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </table>
    </asp:Panel>
</div>
</asp:Content>